Requires: 
Day is at least 30/35/40. (Subject to balance.)
Renown is at least 1050 (Subject to balance.)
Must be on a tundra or snow tile.


this.legend_camp_barbarian_reconnaissance_contract <- this.inherit("scripts/contracts/contract", {
	m = {

	},
	function create()
	{
		this.contract.create();
		this.m.Type = "contract.legend_camp_barbarian_reconnaissance";
		this.m.Name = "Barbarian Reconnaissance";
		this.m.DescriptionTemplates = [
			"Fell winds, the sound of distant pickaxes, and an unnatural chill has spooked the local barbarians. They seek someone expendable to investigate.",
		];

			ID = "Task",
			Title = "At camp...",
			Text = "Milling about the fire with some of the men, your quiet contemplation of days gone is violently interrupted by thunderous drums and the unmistakable blare of a barbarian war horn. Your company responds in kind with a similar chorus of action: armour is donned, steel brandished, and your rehearsed formation struck in blistering speed. Your pride in the company\’s initiative is validated when you see the barbarian host; maybe a dozen men, drummers included stand in staggered lines, with two figures leading the front. One, undoubtedly a chosen from their brutish stature and radiating malice, sets down a log stump, takes a few steps towards you, then plants the other with such force you could mistake the stump as having belonged there to begin with. With a nod of their head, they summon you forward to sit. %SPEECH_ON%I don\’t know Captain, treating with the savages is risky business…%SPEECH_OFF%Indeed. That\’s why %randombrother%\’s coming with you, to deter any… unfortunate misunderstandings. %SPEECH_ON%Wha- oh fark. I mean... I\’m with you, Captain.%SPEECH_OFF%. You approach almost in step with the barbarian\’s drumbeat, stopping mere feet away from the chosen and what you can only assume is the barbarian leader. %SPEECH_ON%Sit.%SPEECH_OFF%, The warlord extends an offering hand to the stump, although in the presence of the towering chosen, it feels more like a command. You sit. He mirrors, eyes locked on you; you glance back to %randombrother% who\’s trying %their_brother% best to mask their nerves against their significantly larger counterpart. Even though you see no weapons on the two savages, you have no doubt the chosen alone could end you both with their bone and fur plated hands before the rest of the company could reinforce. %SPEECH_ON%I know little of your tongue. Wise men from cities of stone, they, as you say, \‘parlayed\’ with my [u]herlidor[\u]. I learned some of your language from them, until they wronged me. Now they furnish my home- I hope you will not be so foolish. We have an offer, what your tribe might call a \‘contract\’.%SPEECH_OFF%You could refuse, but the biting glare from the chosen and his leader suggests their hospitality extends only as far as your perceived value to their goal. Carefully, you respond…",
			Image = "Event_139.png",
			List = [],
			Options = [

				//Option A- Accept	
        Text = "I am listening. What is it your people need?"
          Leads to 1A

        //Option B- Decline
        Text = "We are not interested in dealing with savages, we refuse your offer."
          Leads to 1B
        

//1A: Contract Accepted
        Text ="%SPEECH_ON%For too long, something has fouled our sacred sites. Like rot, it has festered, and we are helpless to cut it out. You will help burn this [u]hrjósetr[\u] .%SPEECH_OFF%While certainly poignant, that doesn\’t give you much to work off, so you inquire details, taking care not to cause any offence that would result in your swift annihilation. %SPEECH_ON%We are bound by [u]trúarsetnes[\u] to commit no violence on our most revered grounds, so we have lowered ourselves by treating with you.%SPEECH_OFF% Of course. You ask if they know what is disrupting their sites, to which the warlord nods his head solemnly. After an awkward pause, you ask what it is.%SPEECH_ON%No. This word, your tongue… it cannot be spoken. You will know it when you find it. Only then, will you know its name, and you will wish you did not.%SPEECH_OFF%You can hear %randombrother% shift in their armour sheepishly, either finally cracking to the chosen\’s oppressively lethal gaze, or being rattled by the chieftain\’s peculiar phrasing. Turning away from the cryptic, you pivot to the practical and ask where to start looking. The barbarian leans down, picking a stick from the ground and using it to point at the earth between you. A few moments later you\’ve both plotted your local environment, a few landmarks, and most importantly, a series of circled points deep above the snowline. %SPEECH_OFF%It needs to die, you know this. You will be rewarded- compensated for your task. When it is done, we will find you, and our \‘contract\’ will be concluded.%SPEECH_OFF%As if knowing you would seek to haggle, he rises to his feet and looks off to the horizon, killing any attempt to negotiate before it could even get started. %SPEECH_ON%For both our sake, city-dweller: good fortune in your hunt.%SPEECH_OFF%With that, he turns his back, revealing the exquisite pelt of a white wolf hugging his body, and walks back towards his host. The chosen remains a moment more, perhaps mourning the lost opportunity to indulge in excessive violence against you and %randombrother%, but soon they trail their leader back to their warband. %SPEECH_ON%Well, uh… Shit, Captain.%SPEECH_OFF%Indeed. You pat %them_brother% on the shoulder, let out a pained grin, and head back to the rest of the company, whose tight formation dissolves around you and your impromptu bodyguard on your return. Questions are loosed like arrows, speculation as to your conversation dispelled by %randombrother%\’s eager recounting. For a moment, you could swear you heard something on the wind- a faint chiselling of steel on stone and a wailing wind almost resembling the howl of something in pain- or fury. The company\’s collective eyes on you snaps you back, %randombrother% asking %SPEECH_ON%So, what now, Captain?%SPEECH_OFF%"
        Option = "Now, we hunt."
        A marker is placed on a snow tile at least 20 units away from the player. When approached, trigger 2A.

//!B: Contract Refused
        Text = "Almost immediately, you regret your choice of words, as does %randombrother%, their eyes burning through the back of your head as though you just signed your death warrants. Perhaps you have. The warlord frowns, looks down to the ground between you both, then back to you. %SPEECH_ON%And yet here I am, dealing with your tribe of savages. But fear not, city people- you will not decorate my home yet, for I understand your fear in this matter. Fell winds rise, our world is changing, and soon, yours will too.%SPEECH_OFF%This ominous threat strangely calms your nerves, for if the barbarians wanted you dead here, they would have shown it by now. Instead, you spy a trace of mourning and uncertainty on the warlords face, so tattooed and scarred, it’s hard to tell where ink and split flesh blend. %SPEECH_ON%Now, leave, and pray we do not meet again, for I doubt we will \‘parlay\’ once more.%SPEECH_OFF%You unwittingly rise at the same time as the warlord, your eyes meeting, and respective bodyguards posturing up towards the other. With a knowing nod, you turn and leave the stumps behind, the company in awe that your head hadn\’t been soundly removed from your shoulders. %randombrother% lets out a gasp so desperate, you almost worry %they_brother% had held their breath through the entire ordeal. \nThe company welcomes you back, breaking formation to huddle around you and your impromptu champion %randombrother%. Questions and curiosity floods the group as you glance back to the meeting site- already the barbarians had vanished seemingly without trace, leaving two stumps, and presumably a patch where %randombrother% had pissed themself in terror. Soon, the questions turn from the curious to the practical, and you snap back in time to register one brother ask what you plan to do; are we fighting, are we following them? \nA cold chill brushes past your neck, earning a shiver and scowl at how cold it already is so early into the year. Tuning your ears, you could almost swear the wind is carrying the sound of steel on stone and ice. In a tone more assured than you have right to command, you tell the company:%SPEECH_ON%We’re leaving.%SPEECH_OFF%"
        Option = "Has it gotten colder, all of a sudden?"
        The contract is refused. It can reappear after 10 days. 

//2A: Ijirok Tracks One
        Image = event_143.png
        Title: "On the trail..."
        Text: "%randombrother% hails you down and says that there\'s something you should come take a look at. Surely something that\'s out in all this ice and nothingness is worth seeing.\nThe sellsword brings you to a cavernous hole in the ground. He lights a torch and steps in, you trailing close behind. There at the bottom you find a few more of your men. They\'re standing around what looks like a sarcophagus made of ice, except there\'s no lid. A frozen blackness cakes the edges of the container. In the corner of the room is an icy corpse stuck to the wall. His hands are at his sides and icicles of blood run from his wrists. Adjacent to it is a pair of clothes hanging from icehooks, but there is no body attached. A trail of blood leads from the clothes to the other man, then back out the cave.%SPEECH_ON%I don\'t know what to make of this sir.%SPEECH_OFF%One mercenary says. You ask the men if they\'ve seen anything in their scouting, and you mean damn near anything. But they all shake their heads no. If something was in that box then it is surely out now. You tell the men to get on out of the cave and back to camp.\nAs you emerge from the icy crypt, the sight of furs and glistening metal draws your eyes to a flanking hill. A single barbarian scout, clad in the pelts and furs of easily a dozen beasts looks down on you and your men. Their piercing stare, then their gentle saunter away tells you you’re on the right track. Whatever that scene in the cave was, it seems it was made by the quarry your barbarian \‘employer\’ wants dead. The sight of one of his men keeping tabs on you sends a cold reminder that your men are mere strangers to this most hostile land."
        Option: "Keep your wits about you, men."
        A marker is placed on a snow tile within 15 units of the player. When approached, trigger 3A.

//3A Ijirok Tracks Two
        Image = event_12.png
        Title: "Closing in..."
        Text: "A blotch in the snowy wastes catches your eye. With a couple of scouts you go out to see what it is, suspecting little more than perhaps an animal carcass or abandoned camp. Instead, you find a party of naked corpses with their bodies crouched as though they were sitting upon chairs. They\'re in a close-knit circle, all facing inward, some with their hands out as if warming them at a fire. You push one of the corpses. As it tips back, the body sitting opposite raises up. %randombrother% jumps away.%SPEECH_ON%By the old gods!%SPEECH_OFF%A rim of flesh runs just beneath the powdered snow, and the ring connects one corpse to the other, a shared desecration beyond your understanding. The skin runs inward, meeting at a fleshen fulcrum which rises out of the snow shaped like some macabre flower pot. Nothing is inside. One of the scouts demands a return to the safety of the company and you very much agree with him./nYou look around for the barbarian tracker from before, but all you discover is a biting gust of wind that leeches your strength and has you reflexively sheltering within your cloak. You think to remark on it to the men, but they all appear oblivious to it, clearly still concerned by the congealed mass of unfortunates you had just discovered."
        Option: "We must be close, steel yourselves."
        A marker is placed on a snow tile within 10 units of the player. When approached, trigger 4A.

//4A Ijirok Tracks Three
        Image = event_143.png
        Title: "During camp..."
        Text: "While camping in the northern wastes, a silhouette approaches, a flat black whose appearance was seemingly cut out of the thin air itself. As it nears, an orange glow blossoms from a horn of fire. The company draw their weapons for what shadowy figure could possibly be out here in all this nothing? Expecting your barbarian shadow, you’re surprised to see a simple, elderly man with a bald pate and bulbous, red nose. If the snow could carve man from granite, this would be the look of its creation. The stranger passes through the camp with the company turning to him and yelling out, but not one sellsword goes near him. He finally leans down and puts the horn to the ground and the snow extinguishes its fire. Then he gets up and keeps going and soon disappears into the fog of night.\n\n  %randombrother% picks up the horn and tips it over. A rose falls out and its clear even in the dark that the petals are soft, but already curling to the brutal cold. You look around for the old man and see his tracks still fresh in the powder. A sinister mood blows through the company, until you remind them you have a contract to fulfill, spurring them to their feet and onto this most peculiar trail."
        Option: "After him!"
        Spawn the Icy Cave within 5 units of the player, and generate footprints between the player and the Cave. When approached, trigger the Icy Cave A2 event.


//5A After the Battle
        Title: "After the battle..."
        Text: "As you depart the cave, a local northerner covered in bear furs stands across the company, seemingly the same barbarian who had trailed you from the beginning of this bizarre hunt. He looks at you and then the cave entrance. He asks.%SPEECH_ON%Do you speak the southern or native tongue?%SPEECH_OFF%Keeping your guard, you confirm the former. He nods.%SPEECH_ON%And what did you see in that cave? Did you see it?%SPEECH_OFF%You tell him you found nothing, only a madman. The stranger smirks.%SPEECH_ON%A madman. A madman, that is what you think you saw. It is within us all to speak warily of the unnatural, but not within us to recognize when nature herself takes a step back. Horrors are easier said than seen. That was no ordinary man, you fool, but the Ijirok, a transient spirit that shifts from one vessel to another. No one really knows what it looks like, the whole world is simply a series of masks and it will happily go from one to the other, usually taking the shape of animals, sometimes a man if he is so weak. It is a being of absolute malice. It cannot be killed, no, it sees death, even its own, as entertainment. It remembers those who escape it, it remembers those it wishes to play with. I pray you\'ve a face worth forgetting.%SPEECH_OFF%You put your hand on the pommel of your sword and tell him that whatever mysticism and mythmaking he\'s got left he can keep to himself. You saw the madman in the cave, and that\'s all he was, a man. The stranger nods again and backs off.%SPEECH_ON%As you say. Regardless, you have held up your end of the bargain you made with my chieftain. Here.%SPEECH_OFF%He slings a sack from his back and places it into the snow between you. %SPEECH_ON% You call it \’compensation\’, or \’payment\’, but this is our gift to you, may it serve you well, for we know you will need it in the days to come.%SPEECH_OFF%With that, the old tracker turns and sets off into the endless white wastes of the north. As a bitter snowstorm picks up, it only takes a minute before the figure is subsumed by the wall of white, and you\’re left with your own thoughts."
        Option: "Let\'s get out of here- preferably somewhere warm for once."
        Roll a random famed piece of barbarian armour.
        Receive one unhold fur cloak.
        Receive 1x Looted Valuables and 1x Ancient Gold Coins
        End contract.

//I am very sorry I have no idea how I would format the pseudocode for such a complex contract that spans the map and various text windows. :ohno:
